# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 590)
        MainWindow.setStyleSheet("background-color: #282a36;\n"
"color: #f8f8f2;\n"
"font: 63 italic 9pt \"Lucida Sans\";\n"
"border-color: #44475a;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 841, 581))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: rgb(165, 188, 229);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: #44475a;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background: #999;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}\n"
"")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Dashboard = QtWidgets.QWidget()
        self.Dashboard.setObjectName("Dashboard")
        self.device_details = QtWidgets.QGroupBox(self.Dashboard)
        self.device_details.setGeometry(QtCore.QRect(0, 10, 225, 79))
        self.device_details.setObjectName("device_details")
        self.gridLayout = QtWidgets.QGridLayout(self.device_details)
        self.gridLayout.setObjectName("gridLayout")
        self.label_deviceName = QtWidgets.QLabel(self.device_details)
        self.label_deviceName.setObjectName("label_deviceName")
        self.gridLayout.addWidget(self.label_deviceName, 0, 0, 1, 1)
        self.lineEdit_deviceName = QtWidgets.QLineEdit(self.device_details)
        self.lineEdit_deviceName.setObjectName("lineEdit_deviceName")
        self.gridLayout.addWidget(self.lineEdit_deviceName, 0, 1, 1, 1)
        self.label_Version = QtWidgets.QLabel(self.device_details)
        self.label_Version.setObjectName("label_Version")
        self.gridLayout.addWidget(self.label_Version, 1, 0, 1, 1)
        self.lineEdit_version = QtWidgets.QLineEdit(self.device_details)
        self.lineEdit_version.setObjectName("lineEdit_version")
        self.gridLayout.addWidget(self.lineEdit_version, 1, 1, 1, 1)
        self.btn_screenshot = QtWidgets.QPushButton(self.Dashboard)
        self.btn_screenshot.setGeometry(QtCore.QRect(0, 302, 91, 31))
        self.btn_screenshot.setStyleSheet("")
        self.btn_screenshot.setObjectName("btn_screenshot")
        self.label_WTC_clock = QtWidgets.QLabel(self.Dashboard)
        self.label_WTC_clock.setGeometry(QtCore.QRect(70, 150, 151, 20))
        self.label_WTC_clock.setStyleSheet("color: #72c1d0;\n"
"font: 63 italic 16pt \"Lucida Sans\";")
        self.label_WTC_clock.setAlignment(QtCore.Qt.AlignCenter)
        self.label_WTC_clock.setObjectName("label_WTC_clock")
        self.label_WTC = QtWidgets.QLabel(self.Dashboard)
        self.label_WTC.setGeometry(QtCore.QRect(0, 150, 61, 20))
        self.label_WTC.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_WTC.setObjectName("label_WTC")
        self.live_data = QtWidgets.QGroupBox(self.Dashboard)
        self.live_data.setGeometry(QtCore.QRect(240, 10, 301, 541))
        self.live_data.setObjectName("live_data")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.live_data)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_num_of = QtWidgets.QLabel(self.live_data)
        self.label_num_of.setObjectName("label_num_of")
        self.gridLayout_2.addWidget(self.label_num_of, 5, 1, 1, 1)
        self.lineEdit_dynamicLogic = QtWidgets.QLineEdit(self.live_data)
        self.lineEdit_dynamicLogic.setObjectName("lineEdit_dynamicLogic")
        self.gridLayout_2.addWidget(self.lineEdit_dynamicLogic, 6, 3, 1, 1)
        self.label_frequency = QtWidgets.QLabel(self.live_data)
        self.label_frequency.setObjectName("label_frequency")
        self.gridLayout_2.addWidget(self.label_frequency, 1, 1, 1, 1)
        self.label_temperature = QtWidgets.QLabel(self.live_data)
        self.label_temperature.setObjectName("label_temperature")
        self.gridLayout_2.addWidget(self.label_temperature, 3, 1, 1, 1)
        self.lineEdit_frequency = QtWidgets.QLineEdit(self.live_data)
        self.lineEdit_frequency.setObjectName("lineEdit_frequency")
        self.gridLayout_2.addWidget(self.lineEdit_frequency, 1, 3, 1, 1)
        self.lineEdit_temperature = QtWidgets.QLineEdit(self.live_data)
        self.lineEdit_temperature.setObjectName("lineEdit_temperature")
        self.gridLayout_2.addWidget(self.lineEdit_temperature, 3, 3, 1, 1)
        self.label_dynamicLogic = QtWidgets.QLabel(self.live_data)
        self.label_dynamicLogic.setStyleSheet("")
        self.label_dynamicLogic.setObjectName("label_dynamicLogic")
        self.gridLayout_2.addWidget(self.label_dynamicLogic, 6, 1, 1, 1)
        self.label_TTF = QtWidgets.QLabel(self.live_data)
        self.label_TTF.setObjectName("label_TTF")
        self.gridLayout_2.addWidget(self.label_TTF, 8, 1, 1, 1)
        self.label_voltage = QtWidgets.QLabel(self.live_data)
        self.label_voltage.setObjectName("label_voltage")
        self.gridLayout_2.addWidget(self.label_voltage, 0, 1, 1, 1)
        self.lineEdit_voltage = QtWidgets.QLineEdit(self.live_data)
        self.lineEdit_voltage.setStyleSheet("")
        self.lineEdit_voltage.setObjectName("lineEdit_voltage")
        self.gridLayout_2.addWidget(self.lineEdit_voltage, 0, 3, 1, 1)
        self.lineEdit_TTF = QtWidgets.QLineEdit(self.live_data)
        self.lineEdit_TTF.setObjectName("lineEdit_TTF")
        self.gridLayout_2.addWidget(self.lineEdit_TTF, 8, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.live_data)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2.addWidget(self.frame_4, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.live_data)
        self.frame.setMinimumSize(QtCore.QSize(0, 320))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2.addWidget(self.frame, 9, 1, 1, 3)
        self.frame_3 = QtWidgets.QFrame(self.live_data)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2.addWidget(self.frame_3, 7, 1, 1, 1)
        self.prediction_modification = QtWidgets.QGroupBox(self.Dashboard)
        self.prediction_modification.setGeometry(QtCore.QRect(550, 10, 279, 541))
        self.prediction_modification.setMinimumSize(QtCore.QSize(0, 0))
        self.prediction_modification.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.prediction_modification.setObjectName("prediction_modification")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.prediction_modification)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.prediction_modification)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.prediction_modification)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 3)
        self.label_11 = QtWidgets.QLabel(self.prediction_modification)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 10, 0, 1, 3)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.prediction_modification)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 0, 3, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.prediction_modification)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.prediction_modification)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 6, 3, 1, 2)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.prediction_modification)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_3.addWidget(self.lineEdit_9, 10, 3, 2, 2)
        self.label_13 = QtWidgets.QLabel(self.prediction_modification)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 2, 3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.prediction_modification)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 1, 3, 1, 2)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.prediction_modification)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 2, 3, 2, 2)
        self.label_16 = QtWidgets.QLabel(self.prediction_modification)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 6, 0, 2, 3)
        self.frame_2 = QtWidgets.QFrame(self.prediction_modification)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 320))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3.addWidget(self.frame_2, 12, 0, 1, 5)
        self.frame_5 = QtWidgets.QFrame(self.prediction_modification)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.prediction_modification)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3.addWidget(self.frame_6, 9, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.Dashboard)
        self.graphicsView.setGeometry(QtCore.QRect(0, 360, 231, 192))
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setObjectName("graphicsView")
        self.Empty = QtWidgets.QPushButton(self.Dashboard)
        self.Empty.setGeometry(QtCore.QRect(130, 302, 101, 31))
        self.Empty.setObjectName("Empty")
        self.btn_openDataFile = QtWidgets.QPushButton(self.Dashboard)
        self.btn_openDataFile.setGeometry(QtCore.QRect(0, 110, 221, 23))
        self.btn_openDataFile.setObjectName("btn_openDataFile")
        self.tabWidget.addTab(self.Dashboard, "")
        self.Analysis = QtWidgets.QWidget()
        self.Analysis.setObjectName("Analysis")
        self.tabWidget.addTab(self.Analysis, "")
        self.RTV = QtWidgets.QWidget()
        self.RTV.setObjectName("RTV")
        self.tabWidget.addTab(self.RTV, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ULTRA-MAIN-PRO"))
        self.device_details.setTitle(_translate("MainWindow", "Device Details"))
        self.label_deviceName.setText(_translate("MainWindow", "Device Name:"))
        self.label_Version.setText(_translate("MainWindow", "Version:"))
        self.btn_screenshot.setText(_translate("MainWindow", "Screenshot"))
        self.label_WTC_clock.setText(_translate("MainWindow", "00:00:00:000"))
        self.label_WTC.setText(_translate("MainWindow", " WTC:  "))
        self.live_data.setTitle(_translate("MainWindow", "Live Data"))
        self.label_num_of.setText(_translate("MainWindow", "Num of "))
        self.label_frequency.setText(_translate("MainWindow", "Frequency"))
        self.label_temperature.setText(_translate("MainWindow", "Temperature:"))
        self.label_dynamicLogic.setText(_translate("MainWindow", "Dynamic Logic:"))
        self.label_TTF.setText(_translate("MainWindow", "TimeToFail:"))
        self.label_voltage.setText(_translate("MainWindow", "Voltage:"))
        self.prediction_modification.setTitle(_translate("MainWindow", "Prediction and Modification"))
        self.label_14.setText(_translate("MainWindow", "Voltage:"))
        self.label_15.setText(_translate("MainWindow", "Frequency"))
        self.label_11.setText(_translate("MainWindow", "TimeToFail:"))
        self.label_12.setText(_translate("MainWindow", "Num of "))
        self.label_13.setText(_translate("MainWindow", "Temperature:"))
        self.label_16.setText(_translate("MainWindow", "Dynamic Logic:"))
        self.Empty.setText(_translate("MainWindow", "Empty"))
        self.btn_openDataFile.setText(_translate("MainWindow", "Open Data File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dashboard), _translate("MainWindow", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Analysis), _translate("MainWindow", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RTV), _translate("MainWindow", "RTV"))
